

CREATE TABLE COMPANY
	(CUI INT PRIMARY KEY,
	 CName VARCHAR(50)
	)

CREATE TABLE DEPARTMENT
	(DepartmentId INT PRIMARY KEY,
	DepartmentName VARCHAR(50),

	)
	
CREATE TABLE EMPLOYER
	(EmployerId INT PRIMARY KEY,
	FirstName VARCHAR(50),
	LastName VARCHAR(50),
	Job VARCHAR(50),
	Salary INT
	
	)

ALTER TABLE EMPLOYER
ADD DepartmentId INT
CONSTRAINT FK_EMPLOYER_DepartmentId
	FOREIGN KEY (DepartmentId)
	REFERENCES DEPARTMENT(DepartmentId)

ALTER TABLE DEPARTMENT
ADD CUI INT
CONSTRAINT FK_DEPARTMENT_COMPANY
	FOREIGN KEY (CUI)
	REFERENCES COMPANY(CUI)


CREATE TABLE CLIENT
	(CNP VARCHAR(50)  PRIMARY KEY,
	FirstName VARCHAR(50),
	LastName VARCHAR(50),
	PhoneNumber VARCHAR(50)
	)



CREATE TABLE OFFER
	(OfferId INT PRIMARY KEY,
	Destination VARCHAR(50),
	NrofDays INT
	)

CREATE TABLE BILL
	(BillId INT PRIMARY KEY,
	 DateofBill VARCHAR(50),
	 ValueofBill INT
	)

ALTER TABLE BILL
ADD EmployerID INT
CONSTRAINT FK_EMPLOYER_BILL
	FOREIGN KEY (EmployerId)
	REFERENCES EMPLOYER(EmployerId)

ALTER TABLE BILL
ADD OfferID INT
CONSTRAINT FK_OFFER_BILL
	FOREIGN KEY (OfferId)
	REFERENCES OFFER(OfferId)

CREATE TABLE ACCOUNTING
	(AId INT PRIMARY KEY,
	 StartDate VARCHAR(50),
	 EndDate VARCHAR(50)
	)

ALTER TABLE ACCOUNTING
ADD CUI INT
CONSTRAINT FK_ACCOUNTING_COMPANY
	FOREIGN KEY (CUI)
	REFERENCES COMPANY(CUI)


CREATE TABLE SPENDING
	(SpendingId INT PRIMARY KEY,
	 descriptionS VARCHAR(50),
	 ValueofBill INT
	)

ALTER TABLE SPENDING 
ADD AId INT
CONSTRAINT FK_ACCOUNTING_SPENDING
	FOREIGN KEY (AId)
	REFERENCES ACCOUNTING(AId)


CREATE TABLE INCOME
	(IncomeId INT PRIMARY KEY,
	 descriptionI VARCHAR(50),
	 ValueofBill INT
	)

ALTER TABLE INCOME
ADD BillId INT
CONSTRAINT FK_BILL_INCOME
	FOREIGN KEY (BillId)
	REFERENCES BILL(BillId)	
	
ALTER TABLE INCOME
ADD AId INT
CONSTRAINT FK_ACCOUNTING_INCOME
	FOREIGN KEY (AId)
	REFERENCES ACCOUNTING(AId)



CREATE TABLE DESTINATION
	(destId INT PRIMARY KEY,
	 hotel VARCHAR(50),
	 destination_name VARCHAR(50)
	)

CREATE TABLE BILL_CLIENT
	(BillId INT REFERENCES BILL(BillId),
	CNP VARCHAR(50) REFERENCES CLIENT(CNP),
	 PRIMARY KEY(BillID,CNP)

)

CREATE TABLE OFFER_DESTINATION
	(OfferId INT REFERENCES OFFER(OfferiD),
	 destId INT REFERENCES DESTINATION(destId),
	 PRIMARY KEY(OfferId,destId)

)


